name: ci

on:
  - push
  - pull_request

jobs:
  linting:
    uses: ./.github/workflows/linting.yml

  test_os:
    uses: ./.github/workflows/testing_os.yml
    needs: linting

  test_spark:
    uses: ./.github/workflows/testing_spark.yml
    needs: linting
