name: ci

on:
  - push
  - pull_request

jobs:
  gitleaks:
    uses: ./.github/workflows/gitleaks.yml

  linting:
    uses: ./.github/workflows/linting.yml
    needs: gitleaks

  test_os:
    uses: ./.github/workflows/testing_os.yml
    needs: linting

  test_py_version:
    uses: ./.github/workflows/testing_py_version.yml
    needs: linting

  test_spark:
    uses: ./.github/workflows/testing_spark.yml
    needs: linting
