name: docs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[docs]'
      - name: Build HTML
        run: |
          sphinx-apidoc -P -o docs src/sparkchecker
          make -C docs clean
          make -C docs html
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Stage changes
          git add -A

          # Commit only if there are changes
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update documentation"

            # Determine the target branch
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              TARGET_BRANCH=${{ github.head_ref }}
            else
              TARGET_BRANCH=${{ github.ref_name }}
            fi

            # Push changes
            git push origin HEAD:$TARGET_BRANCH
          else
            echo "No changes to commit."
          fi
