name: test_spark

on:
  - workflow_call

jobs:
  test_spark_version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyspark-version: ["pyspark>=3.3.0,<3.4.0", "pyspark>=3.4.0,<3.5.0", "pyspark>=3.5.0"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir "${{ matrix.pyspark-version }}"
        pip install '.[test]'
    - name: Starts testing
      run: pytest --cov
    - name: Show coverage
      run: coverage report
