name: test

on:
  - workflow_call

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11']
        pyspark-version: ["pyspark>=3.4.0,<3.5.0", "pyspark>=3.5.0"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir "${{ matrix.pyspark-version }}"
        pip install '.[test]'
    - name: Starts testing
      run: pytest --cov
    - name: Show coverage
      run: coverage report
